[WIP] JSONRPC validator
nimiq/woocommerce-gateway-nimiq pull request #5
Opened 2019-01-13 07:54 UTC by terorie

Implements #3 :)

2019-01-13 19:14 UTC, sisou requested changes
Thank you for this! I added some improvement suggestions.

2019-01-13 19:14 UTC, sisou commented on woocommerce-gateway-nimiq.php
> +					'type'        => 'textarea',
1. I would like to see the name of the setting be prefixed with the service type it is for, like `json-rpc_url`.
2. The setting should come directly after the service selector setting IMHO. 
3. It should be a `text` type, as the url is a single line setting.

2019-01-13 19:14 UTC, sisou commented on js/settings.js
> +            '#url',
This is not the correct ID as generated by woocommerce in the settings page.

2019-01-13 19:20 UTC, sisou requested changes

2019-01-13 19:20 UTC, sisou commented on validation_services/json_rpc.php
> +        if ( $this->transaction->data === null ) {
Every other property is behind the `->result` property. I guess `data` should too?

2019-01-13 19:26 UTC, riptl commented on js/settings.js
> +            '#url',
Good catch!

2019-01-14 17:19 UTC, sisou approved these changes

2019-01-14 17:19 UTC, merged