JSON-RPC basic authentication
nimiq/woocommerce-gateway-nimiq pull request #9
Opened 2019-01-16 12:09 UTC by terorie

Solves #8 

Not tested yet, I'll do that later.

2019-01-16 12:21 UTC, sisou requested changes

2019-01-16 12:21 UTC, sisou commented on js/settings.js
> +                ].forEach(tag => $(tag).closest('tr').removeClass('hidden'));
You can but the list of IDs inside the jquery constructor. Jquery can work with a set of elements. That would prevent having to create a new jquery instance for each field.

2019-01-16 12:21 UTC, sisou commented on validation_services/json_rpc.php
> +            $authorization = 'Basic ' . base64_encode( $username . $password );
Missing a colon `:` between the username and password here.

2019-01-16 12:29 UTC, riptl commented on validation_services/json_rpc.php
> +            $authorization = 'Basic ' . base64_encode( $username . $password );
thanks!

2019-01-17 10:53 UTC, sisou commented on validation_services/json_rpc.php
> +            $authorization = 'Basic ' . base64_encode( $username . $password );
I meant, between the *username* and *password* ;p

2019-01-17 10:55 UTC, sisou commented on validation_services/json_rpc.php
> +            $authorization = 'Basic ' . base64_encode( $username . $password );
Compare again with https://github.com/nimiq-network/core/blob/master/clients/nodejs/modules/JsonRpcServer.js#L165

2019-01-17 13:07 UTC, terorie commented on validation_services/json_rpc.php
> +            $authorization = 'Basic ' . base64_encode( $username . $password );
@sisou That's so embarrassing 😂 I know how Basic auth works, I swear

2019-01-17 13:15 UTC, terorie commented on validation_services/json_rpc.php
> +            $authorization = 'Basic ' . base64_encode( $username . $password );
I'm amending the last commit so no-one sees it

2019-01-23 00:37 UTC, sisou commented
Have you tested this yet in a local setup, @terorie?

2019-01-23 00:38 UTC, sisou approved these changes

2019-05-10 21:52 UTC, sisou approved these changes

2019-05-10 21:52 UTC, merged